name: Builder
on:
  workflow_dispatch: {}
  push:
    paths:
    - 'builder/**'
    - 'buildpacks/**'
    - 'tests/**'
    branches:
    - '**'
    tags:
    - 'builder/*'

jobs:
  buildpack-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    - run: go version
    - name: Run Buildpack Tests
      run: make buildpack-tests

  smoke-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    - run: go version
    - name: Create builder
      run: make builder
    - name: Run Smoke Tests
      run: make smoke-test

  publish:
    needs: [buildpack-tests,smoke-tests]
    runs-on: ubuntu-latest
    if: startsWith(github.ref,'refs/tags/builder/')
    env:
      build: release
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    - name: Write credentials for GCS
      env:
        GS_SERVICE_KEY: ${{ secrets.GS_SERVICE_KEY }}
      run: printf '%s' "${GS_SERVICE_KEY}" > /tmp/cnr-gcs-secret.json
    - name: Docker login
      run: docker login -u _json_key --password-stdin "https://us.gcr.io" < /tmp/cnr-gcs-secret.json
    - name: Build
      run: make build=${{env.build}} builder
    - name: Publish
      run: make build=${{env.build}} publish-builder
